---
- hosts: all
  become: yes  # To ensure we have the necessary permissions
  tasks:
    # - name: Backing up /etc/ssh/sshd_config
    #   shell: cp -prf /etc/ssh/sshd_config /etc/ssh/sshd_config.org

    - name: Update SSHD config to remediate weak key algorithms
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^{{ item.regexp }}'
        line: '{{ item.line }}'
      with_items:
        # - { regexp: '^HostKeyAlgorithms', line: 'HostKeyAlgorithms ssh-ed25519,ecdsa-sha2-nistp521,ssh-rsa' }
        - { regexp: '^KexAlgorithms', line: 'KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256' }
        - { regexp: '^Ciphers', line: 'Ciphers aes128-ctr,aes192-ctr,aes256-ctr' }
        - { regexp: '^MACs', line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com' }
    
    - name: Uncomment the /etc/sysconfig/sshd to opt out the crypto policy for sshd
      lineinfile:
        path: /etc/sysconfig/sshd
        regexp: '^# CRYPTO_POLICY='
        line: 'CRYPTO_POLICY='
        state: present

    - name: Restarting sshd service
      service: name=sshd state=restarted
